[2024-10-21T01:17:49.881+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:17:49.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:17:49.885+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:49.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:17:53.280+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:17:53.285+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:17:53.311+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:17:53.311+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:17:53.330+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.326+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:17:53.331+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.330+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:17:53.343+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:17:53.680+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.679+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:elt
[2024-10-21T01:17:53.691+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.691+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:elt
[2024-10-21T01:17:53.700+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.700+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:elt
[2024-10-21T01:17:53.709+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.709+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:elt
[2024-10-21T01:17:53.715+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.715+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:elt
[2024-10-21T01:17:53.730+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.729+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:elt
[2024-10-21T01:17:53.738+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.738+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:elt
[2024-10-21T01:17:53.739+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.738+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:17:53.752+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.751+0000] {dag.py:3262} INFO - Creating ORM DAG for elt
[2024-10-21T01:17:53.761+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:17:53.761+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:17:53.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 3.904 seconds
[2024-10-21T01:18:24.187+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:18:24.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:18:24.195+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:24.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:18:24.767+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:18:24.768+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:18:24.772+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:18:24.773+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:18:24.786+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:24.782+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:18:24.787+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:24.786+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:18:24.791+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:18:24.811+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:24.810+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:18:24.826+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:24.826+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:18:24.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.661 seconds
[2024-10-21T01:18:55.119+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:18:55.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:18:55.123+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:55.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:18:55.708+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:18:55.709+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:18:55.710+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:18:55.711+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:18:55.714+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:55.713+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:18:55.715+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:55.714+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:18:55.716+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:18:55.732+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:55.732+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:18:55.743+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:18:55.743+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:18:55.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.654 seconds
[2024-10-21T01:19:25.914+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:19:25.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:19:25.919+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:25.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:19:26.589+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:19:26.591+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:19:26.594+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:19:26.594+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:19:26.602+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:26.600+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:19:26.602+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:26.602+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:19:26.604+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:19:26.621+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:26.621+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:19:26.633+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:26.633+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:19:26.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.736 seconds
[2024-10-21T01:19:57.032+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:19:57.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:19:57.043+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:57.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:19:57.513+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:19:57.513+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:19:57.516+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:19:57.517+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:19:57.521+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:57.520+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:19:57.521+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:57.521+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:19:57.523+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:19:57.549+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:57.549+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:19:57.561+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:19:57.561+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:19:57.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.548 seconds
[2024-10-21T01:20:27.738+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:20:27.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:20:27.751+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:27.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:20:28.599+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:20:28.600+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:20:28.603+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:20:28.603+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:20:28.609+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:28.607+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:20:28.609+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:28.609+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:20:28.612+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:20:28.627+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:28.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:20:28.641+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:28.641+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-19 12:00:00+00:00, run_after=2024-10-20 12:00:00+00:00
[2024-10-21T01:20:28.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.986 seconds
[2024-10-21T01:20:59.143+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:20:59.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:20:59.168+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:20:59.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:21:00.182+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:21:00.183+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:21:00.188+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:21:00.189+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:21:00.197+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:00.193+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:21:00.197+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:00.197+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:21:00.210+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:21:00.252+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:00.251+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:21:00.271+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:00.271+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:21:00.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 1.158 seconds
[2024-10-21T01:21:31.342+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:21:31.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:21:31.352+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:31.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:21:32.849+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:21:32.850+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:21:32.854+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:21:32.855+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:21:32.860+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:32.859+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:21:32.861+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:32.861+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:21:32.864+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:21:32.917+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:32.917+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:21:32.945+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:21:32.944+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:21:32.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 1.677 seconds
[2024-10-21T01:22:03.579+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:22:03.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:22:03.590+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:03.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:22:04.309+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:22:04.310+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:22:04.311+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:22:04.312+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:22:04.314+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:04.314+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:22:04.315+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:04.315+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:22:04.317+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:22:04.348+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:04.348+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:22:04.363+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:04.363+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:22:04.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.805 seconds
[2024-10-21T01:22:34.770+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:22:34.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:22:34.791+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:34.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:22:35.381+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:22:35.381+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:22:35.383+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:22:35.383+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:22:35.386+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:35.386+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:22:35.387+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:35.387+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:22:35.389+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:22:35.409+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:35.409+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:22:35.428+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:22:35.428+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:22:35.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.680 seconds
[2024-10-21T01:23:05.853+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:23:05.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:23:05.859+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:05.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:23:06.362+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:23:06.363+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:23:06.364+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:23:06.365+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:23:06.368+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:06.367+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:23:06.368+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:06.368+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:23:06.370+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:23:06.386+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:06.386+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:23:06.408+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:06.408+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:23:06.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.577 seconds
[2024-10-21T01:23:36.751+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:23:36.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:23:36.766+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:36.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:23:37.288+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:23:37.289+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:23:37.291+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:23:37.291+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:23:37.295+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:37.294+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:23:37.295+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:37.295+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:23:37.297+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:23:37.334+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:37.334+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:23:37.347+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:23:37.347+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:23:37.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.611 seconds
[2024-10-21T01:24:08.003+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:24:08.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:24:08.009+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:08.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:24:08.301+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:24:08.304+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:24:08.308+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:24:08.308+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:24:08.319+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:08.318+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:24:08.319+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:08.319+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:24:08.321+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:24:08.339+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:08.339+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:24:08.360+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:08.360+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:24:08.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.386 seconds
[2024-10-21T01:24:38.710+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:24:38.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:24:38.716+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:38.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:24:39.024+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:24:39.025+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:24:39.029+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:24:39.029+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:24:39.034+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:39.033+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:24:39.034+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:39.034+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:24:39.037+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:24:39.059+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:39.058+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:24:39.074+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:24:39.074+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:24:39.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.385 seconds
[2024-10-21T01:25:09.636+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:25:09.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:25:09.643+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:09.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:25:09.948+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:25:09.949+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:25:09.954+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:25:09.954+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:25:09.960+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:09.958+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:25:09.960+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:09.960+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:25:09.963+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:25:09.985+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:09.985+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:25:10.003+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:10.002+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:25:10.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.388 seconds
[2024-10-21T01:25:40.868+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:25:40.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:25:40.882+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:40.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:25:41.288+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:25:41.288+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:25:41.293+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:25:41.293+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:25:41.299+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:41.297+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:25:41.300+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:41.299+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:25:41.302+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:25:41.341+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:41.340+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:25:41.363+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:25:41.363+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:25:41.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.538 seconds
[2024-10-21T01:26:11.771+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:26:11.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:26:11.782+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:11.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:26:12.069+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:26:12.070+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:26:12.078+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:26:12.078+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:26:12.084+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:12.083+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:26:12.084+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:12.084+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:26:12.087+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:26:12.110+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:12.110+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:26:12.125+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:12.125+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:26:12.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.376 seconds
[2024-10-21T01:26:42.503+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:26:42.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:26:42.578+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:42.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:26:43.232+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:26:43.233+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:26:43.245+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:26:43.245+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:26:43.255+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:43.253+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:26:43.255+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:43.255+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:26:43.265+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:26:43.319+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:43.319+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:26:43.355+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:26:43.355+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:26:43.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.918 seconds
[2024-10-21T01:27:14.430+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:27:14.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:27:14.440+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:14.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:27:14.760+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:27:14.761+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:27:14.765+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:27:14.765+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:27:14.770+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:14.769+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:27:14.770+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:14.770+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:27:14.772+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:27:14.796+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:14.795+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:27:14.811+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:14.811+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:27:14.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.420 seconds
[2024-10-21T01:27:44.940+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:27:44.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:27:44.949+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:44.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:27:45.285+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:27:45.285+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:27:45.296+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:27:45.297+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:27:45.303+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:45.302+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:27:45.304+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:45.304+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:27:45.306+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:27:45.334+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:45.334+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:27:45.350+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:27:45.350+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:27:45.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.429 seconds
[2024-10-21T01:28:15.985+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:28:15.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:28:15.994+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:15.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:28:16.320+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:28:16.321+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:28:16.340+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:28:16.341+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:28:16.346+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:16.345+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:28:16.347+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:16.346+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:28:16.350+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:28:16.380+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:16.380+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:28:16.414+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:16.413+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:28:16.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.460 seconds
[2024-10-21T01:28:46.778+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/elt.py
[2024-10-21T01:28:46.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/elt.py for tasks to queue
[2024-10-21T01:28:46.787+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:46.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/elt.py
[2024-10-21T01:28:47.069+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:28:47.070+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:28:47.076+0000] {logging_mixin.py:190} INFO - Searching in path: dags/sql_files/l2
[2024-10-21T01:28:47.077+0000] {logging_mixin.py:190} INFO - SQL files found: ['fact_items_information.sql', 'dim_item.sql']
[2024-10-21T01:28:47.083+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:47.081+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/fact_items_information.sql
[2024-10-21T01:28:47.083+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:47.083+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dags/sql_files/l2/dim_item.sql
[2024-10-21T01:28:47.086+0000] {processor.py:925} INFO - DAG(s) 'elt' retrieved from /opt/airflow/dags/elt.py
[2024-10-21T01:28:47.126+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:47.125+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-21T01:28:47.142+0000] {logging_mixin.py:190} INFO - [2024-10-21T01:28:47.142+0000] {dag.py:4180} INFO - Setting next_dagrun for elt to 2024-10-20 12:00:00+00:00, run_after=2024-10-21 12:00:00+00:00
[2024-10-21T01:28:47.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/elt.py took 0.403 seconds
