[2024-10-20T06:03:29.091+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T06:03:29.103+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt.transform_data.l2 manual__2024-10-20T06:01:44.559696+00:00 [queued]>
[2024-10-20T06:03:29.108+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt.transform_data.l2 manual__2024-10-20T06:01:44.559696+00:00 [queued]>
[2024-10-20T06:03:29.108+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-20T06:03:29.117+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): transform_data.l2> on 2024-10-20 06:01:44.559696+00:00
[2024-10-20T06:03:29.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1483) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-20T06:03:29.128+0000] {standard_task_runner.py:72} INFO - Started process 1485 to run task
[2024-10-20T06:03:29.128+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt', 'transform_data.l2', 'manual__2024-10-20T06:01:44.559696+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp616ftyzn']
[2024-10-20T06:03:29.137+0000] {standard_task_runner.py:105} INFO - Job 262: Subtask transform_data.l2
[2024-10-20T06:03:30.574+0000] {task_command.py:467} INFO - Running <TaskInstance: elt.transform_data.l2 manual__2024-10-20T06:01:44.559696+00:00 [running]> on host 3b0481c80fd2
[2024-10-20T06:03:30.671+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mherszage' AIRFLOW_CTX_DAG_ID='elt' AIRFLOW_CTX_TASK_ID='transform_data.l2' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T06:01:44.559696+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T06:01:44.559696+00:00'
[2024-10-20T06:03:30.673+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T06:03:30.703+0000] {sql.py:266} INFO - Executing: None
[2024-10-20T06:03:30.710+0000] {base.py:84} INFO - Retrieving connection 'redshift_default'
[2024-10-20T06:03:30.713+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 450, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-10-20T06:03:30.738+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt, task_id=transform_data.l2, run_id=manual__2024-10-20T06:01:44.559696+00:00, execution_date=20241020T060144, start_date=20241020T060329, end_date=20241020T060330
[2024-10-20T06:03:30.751+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T06:03:30.752+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 262 for task transform_data.l2 (List of SQL statements is empty; 1485)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 450, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-10-20T06:03:30.897+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T06:03:31.174+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
